# Generated by Django 3.2.9 on 2022-02-19 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Contract Number')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Image')),
                ('vendor', models.CharField(max_length=150, verbose_name='Vendor')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('renewble', models.BooleanField(verbose_name='Renewble')),
                ('renewal_duration', models.IntegerField(verbose_name='Renewal Duration ')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('auth_status', models.BooleanField(default=False, max_length=150, verbose_name='Auth Status')),
                ('type', models.CharField(max_length=150, verbose_name='Contract Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('contract_with', models.CharField(max_length=150, verbose_name='Contract With')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('authorizor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorizor', to=settings.AUTH_USER_MODEL)),
                ('department', models.ManyToManyField(blank=True, to='contracts.Department')),
                ('inputer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
