# Generated by Django 3.2.9 on 2022-02-23 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='image',
        ),
        migrations.AddField(
            model_name='contract',
            name='pdf',
            field=models.FileField(default=datetime.datetime(2022, 2, 23, 11, 29, 18, 967768, tzinfo=utc), upload_to='files/', verbose_name='File'),
            preserve_default=False,
        ),
    ]
